# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ODS.IM---网络激活大师
keywords: ODS.IM,网络激活大师,CAD安装,CAD安装包,CAD激活,CAD破解,CAD2006,CAD2007,CAD2008,CAD2009,CAD2010,CAD2011,CAD2012,CAD2013,CAD2014, CAD2015,CAD2016,CAD2017,CAD2018,CAD2019,CAD2020,CAD2021,CAD2022,CORELdraw安装,CORELdraw激活,photoshop,adboe,office365,Microsoft365，Windows密钥,office密钥,office2021激活密钥
description: ODS.IM,网络激活大师,CAD安装,CAD安装包,CAD激活,CAD破解,CAD2006,CAD2007,CAD2008,CAD2009,CAD2010,CAD2011,CAD2012,CAD2013,CAD2014, CAD2015,CAD2016,CAD2017,CAD2018,CAD2019,CAD2020,CAD2021,CAD2022,CORELdraw安装,CORELdraw激活,photoshop,adboe,office365,Microsoft365，Windows密钥,office密钥,office2021激活密钥
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ods.im" # the base hostname & protocol for your site

# permalink: /:year/:month/:day/:title/
permalink: /:title/

# other links
# twitter_username:
# facebook_username: gaohaoyang.water
# github_username:  Gaohaoyang
# email: gaohaoyang126@126.com
# weibo_username: 3115521wh
# zhihu_username: gaohaoyang
# linkedIn_username: gaohaoyang
# dribbble_username:
# qq_username:
taobao_username: ms365.taobao.com

# description_footer: 本站记录我前端之旅的沿途风景！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
# duoshuo_shortname: 
# disqus_shortname: 
# changyan_shortname: ODS

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?66f1422db50724bccb84808f04c2cd93";
# xxxxx字符串
baidu_tongji_id: 66f1422db50724bccb84808f04c2cd93
# google_analytics_id: UA-72449510-4 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 10

plugins:
  - jekyll-paginate
